add img
laposhko/NotWizards.YET pull request #18
Opened 2024-03-18 21:53 UTC by VictoriaKiselova

2024-03-18 22:39 UTC, laposhko commented on src/partials/projects.html
> +              <source media="(max-width: 375px)" srcset="
min-width

2024-03-18 22:47 UTC, laposhko requested changes
1)remove font-family: Inter Tight; from css
2)fix max-width: 375px 
3) .container styles are in styles.css, remove it from project.css

2024-03-19 05:14 UTC, VictoriaKiselova commented
change max-width, del font-family.

2024-03-19 05:14 UTC, VictoriaKiselova commented on src/partials/projects.html
> +              <source media="(max-width: 375px)" srcset="
+

2024-03-19 07:47 UTC, laposhko approved these changes

2024-03-19 07:48 UTC, merged